server:
  host:
    mariadb: 127.0.0.1
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

spring:
  profiles:
    group:
      master: common, master
      slave: common, slave

---
server:
  port: 9080

spring:
  config:
    activate:
      on-profile: master, test
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://${server.host.mariadb}:3309/replica_master
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #auto: create
          auto: validate
---
server:
  port: 9081

spring:
  config:
    activate:
      on-profile: slave
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://${server.host.mariadb}:3309/replica_slave
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #auto: create
          auto: validate

master-server:
  uri: ws://127.0.0.1:9080/replica
---
spring:
  config:
    activate:
      on-profile: common, test
#  task:
#    execution:
#      pool:
#        core-size: 5   # 기본 스레드 수
#        max-size: 10    # 최대 스레드 수
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: true   # 속성이 없는 경우 오류 발생 (true) -> 무시 (false)
  jpa:
    properties:
      hibernate:
        format_sql: true    # DB 쿼리 포멧팅
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  file:
    path: ./logs
  level:
#    com:
#      zaxxer:
#        hikari:
#          HikariConfig: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE